 /*
  * This file was generated by the devil.
  * Please do not edit it directly or you will go to hell
  */

#ifndef _CONFIG_H_
#define _CONFIG_H_

# define SERIAL_DEBUG 1
# define VGA_DEBUG    2

# define USERLAND

#endif /* _CONFIG_H_ */
