 /*
  * This file was generated by the devil.
  * Please do not edit it directly or you will go to hell
  */

#ifndef _CONFIG_H_
#define _CONFIG_H_

# define USERLAND

# define DEBUG

#endif /* _CONFIG_H_ */
